### PR TITLE
run tests by calling asdf:test-system

### PR DESCRIPTION
**Pull request by guicho271828**

### CODE REVIEW

**Comment by guicho271828** [comment]
sorry, WIP

**Comment by guicho271828** [comment]
Rebased onto master. I wrote a set of preliminary tests, but it doesnt seem to work. What's wrong?

**Comment by cosmos72** [comment]
Thanks for the fixes and the tests :)

I reorganized them a bit, and (fiveam:run! 'cl-parametric-types.test::less) now succeeds.
Instead (fiveam:run! 'cl-parametric-types.test::pair) exposes a bug... the specialization of MAKE-PAIR is looked for in the wrong package, I will fix it ASAP

**Comment by cosmos72** [comment]
Fixed in 7e19936f25983cd77b7aecf0e6cf171c53340aa8

**Pull request closed without merging**
